// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0grfxC-5EKk4xzJVZGt1CdnudU5K-pQ0',
    appId: '1:1049331388664:web:984aebd84d3656ad3fab0d',
    messagingSenderId: '1049331388664',
    projectId: 'tugas10-61858',
    authDomain: 'tugas10-61858.firebaseapp.com',
    storageBucket: 'tugas10-61858.firebasestorage.app',
    measurementId: 'G-P5MRPQK4ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYvpiMjv0vnzwaeLlFUXK-ICgafwkyMqo',
    appId: '1:1049331388664:android:99c416ff2b8a8c6d3fab0d',
    messagingSenderId: '1049331388664',
    projectId: 'tugas10-61858',
    storageBucket: 'tugas10-61858.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTSi0RthuJBzzZGUUkxaJkKoUKpXPbqMY',
    appId: '1:1049331388664:ios:b69214b137963eaa3fab0d',
    messagingSenderId: '1049331388664',
    projectId: 'tugas10-61858',
    storageBucket: 'tugas10-61858.firebasestorage.app',
    iosBundleId: 'com.example.tugas10',
  );
}
