// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM0TqTsujnyPpsjYE5q4wVZCoIiLV3hQ0',
    appId: '1:719698346066:web:366fb05cb6a95d60e69f8b',
    messagingSenderId: '719698346066',
    projectId: 'tugas9-7fb43',
    authDomain: 'tugas9-7fb43.firebaseapp.com',
    storageBucket: 'tugas9-7fb43.firebasestorage.app',
    measurementId: 'G-7FDRHGY3WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9lNHIWMCn_wLH8gIgytdJs_rnmAze8w8',
    appId: '1:719698346066:android:984bd4e04999f42de69f8b',
    messagingSenderId: '719698346066',
    projectId: 'tugas9-7fb43',
    storageBucket: 'tugas9-7fb43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdgGJGoUeXT0yHw4ypnwrQOQvTq5rG71Q',
    appId: '1:719698346066:ios:1e16bba104623d45e69f8b',
    messagingSenderId: '719698346066',
    projectId: 'tugas9-7fb43',
    storageBucket: 'tugas9-7fb43.firebasestorage.app',
    iosBundleId: 'com.example.tugas9',
  );
}
